components/about/history/first.vue, components/about/history/second.vue, components/about/history/third.vue, components/about/org/administrative.vue, components/about/org/judicial.vue, components/about/org/legislation.vue, components/index/message.vue, components/index/topnews.vue, pages/about/charter.vue, pages/about/history.vue, pages/about/index.vue, pages/about/laws.vue, pages/about/org.vue, pages/about/word.vue, pages/index.vue
Now the about page are avaliable.
1. The page is just a simple page that use h1 to recognize each other.
=> Complete a part of router.

assets/css/main.css, components/header.vue, pages/account/login.vue
1. delete the text-align: center property in main.css.
2. now the Login page is available (but simple).
=> Complete the simple Login page.

components/header.vue, pages/account/login.vue
1. fix the login button of Login page do not call the submit function.
=> Fix the association of button.

pages/account/login.vue
1. fix all error of eslint in login.vue
=> Fix the eslint error.

pages/account/registry.vue
have some attributes 
eg : name, student id
=> make brief login page

components/announcement/important.vue, pages/account/login.vue, pages/announcement/important.vue, pages/announcement/text.vue
1. modify the page/announcement/index.vue h1 value.
2. add page/announcement/important.vue
3. add page/announcement/text.vue
4. add components/announcement/
=> Modify page/announcement/ structure. 

components/announcement/message.vue, components/announcement/topnews.vue, pages/announcement/message.vue, pages/announcement/topnews.vue
1. Change the important.vue to topnews.vue.
2. Chnage the text.vue to message.vue.
=> Modify the file name of announcmenet/

components/announcement/message.vue, components/announcement/post.vue, pages/announcement/post.vue
1. use components /components/announcement/post in page/announcement/post
=> Complete simple post page.

components/announcement/post.vue
1. Add selectable menu to choose the type of post.
2. use form tag to wrap up the all input element.
=> Add selectable menu of /component/announcement/post.

components/announcement/post.vue, nuxt.config.js
1. Complete part of the style of editor.
2. Group and display the editor of command.
3. Modify the whole components of upper container "div" to "form".
=> Complete the style of editor

components/announcement/post.vue
1. dynamically generating the color palette of editor
2. change the timer code to mounted function.
=> Complete partial javascript of editor.

components/announcement/post.vue
1. Now need to deal with the image problem.
2. There will be an upload window appear to let user choose the image file.
3. Most of the editor feature now is available.
=> Complete the javascript of editor.

components/announcement/post.vue
1. Use Object Urls to display the preview of an image.
2. Rewrite the operation function structure.
=> Complete the feature of preview image of editor.

.gitignore, api/index.js, api/routes/post.js, components/announcement/post.vue, package-lock.json
Connect the image upload between frontend and backend.
1. Use object url to preview the image.
2. Use FormData to send the target images to backend.
3. Backend will receive the file and create corresponding folder to store the images.
4. The folder naming rules will use post title and append a uuid.
5. Register a rootPath in /api/index.js
6. Add body-parser in /api/index.js to parser some ASCII url.
7. Add Title column in editor.
8. Add /static/uploads folder in .gitignore.
9. If the post mode is message, then poster cannot upload any image.
=> Feature announcement

api/index.js, api/routes/post.js, components/announcement/post.vue
1. Fix the problem that poster cannot uploads the same image in succession.
2. Modify the action of try/catch after catch error that was not EERROR.
3. Revoke the object url after append the information on img tag.
=> Fix the problem of editor.

components/announcement/editor/post.vue, components/announcement/editor/resizeable-img.vue, pages/announcement/post.vue
1. Use canvas and mouse event to resize the image.
2. Insert the resizeable image as a component in /components/announcement/editor/post.vue.
3. Sort out the structure of the announcement components folder.
=> Complete resizeable image of component of editor.

components/announcement/editor/post.vue, components/announcement/editor/resizeable-img.vue
1. Fix the problem that post.vue can not fetch the image file.
2. Transfer the canvas data to file data.
=> Fix the problem of uploading image.

api/index.js, api/routes/login.js, package-lock.json, package.json, pages/account/login.vue, plugins/axios.js
Set simple cookie
Using connect-session-sequelize to save session to mysql
You should change model/config/index.js that it connect to your database
You can know whether it is loginning by requesting to '/' in api/index.js
=> Feature login

.vscode/settings.json, components/policy/proposal.vue, pages/policy/index.vue, pages/policy/proposal.vue
pages/policy/propsal  display proposal pages
components/policy/proposal  implement proposal editor
=> new proposal page created

api/routes/login.js, pages/account/login.vue, pages/account/registry.vue
1. Add more detail of registry columns in registry page.
2. Move the mechanism for checking passwords to frontend.
3. Expire the cookie when the user logout.
=> Add columns in registry page.

api/routes/login.js, package-lock.json, store/index.js
1. Modify the ogin API to return a json object.
2. Need to get the permission from operation result.
=> Modify the login API return format.

api/routes/login.js, store/index.js
1. Correct the registration status of the wrong column.
=> Fix the problem of login status.

api/routes/login.js, package-lock.json, package.json, pages/account/registry.vue
Reverts toolbuddy/NCKU-SU-Website#40
=> Revert "Use email to send verification code"

components/announcement/message-column.vue, components/announcement/pagination.vue, components/announcement/topnews-column.vue, components/header.vue, pages/announcement/topnews.vue
1. Add the read all text label when the content is too large and splited.
2. Complete simple pagination component.
=>  Complete simple pagination component.

api/routes/login.js, package-lock.json, pages/account/login.vue, pages/account/verification.vue, store/index.js
1. Use try/catch in login/logout async function.
2. Add verification page.
=> Modify the store code.

api/routes/change_pwd.js, api/routes/login.js, model/query/account.js, pages/account/changePassword.vue, store/index.js
1. Modify the login/change_pwd API of checking operation return value.
2. Now the change passwrod when login feature is available.
=> Complete the forget password between frontend and backend.

components/account/croppable-img.vue, pages/account/index.vue
1. Now the croppable image components can crop the image.
2. Need to let the original image can also zoom in and out.
3. Test the croppable image at account/ page.
=> Complete part of croppable image components.

components/account/croppable-img.vue, pages/account/index.vue
1. Pass the prop to set the croppable image view/cut size.
2. Rewrite the croppable image structure
3. Need to fit to the RWD.
4. Now the cut button click will display the cutted image in browser that is not chrome.
=> Complete the croppable image component.

api/routes/post.js, api/routes/uploadFile.js, components/announcement/editor/post.vue, components/announcement/editor/upload-file-zone.vue
1. Modify the API of upload file. Now you need to append path field to assign the target upload path.
2. Connect the file upload between frontend and backend.
=> Connect the file upload between frontend and backend.

api/index.js, api/routes/bighead.js, components/account/croppable-img.vue, pages/account/registry.vue
1. Now can upload the profile image in registry page.
2. Modify the naming rules of the bighead API.
3. Add rootPath constant globally.
=> Upload the profile image by using API.
